include: jumia.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://www.jumia.com.ng/catalog/?q={}
    poster_post_identifiers_retriever_module:
      regex: jumia.com.ng\/(.+).html
    post_identifiers_retriever_module:
      regex: jumia.com.ng\/(.+).html
    price_retriever_module:
      replace_old: \â‚¦
      replace_new: NGN
  post_information_retriever_module:
    post_url_template: https://www.jumia.com.ng/{}.html