include: jumia.yaml
framework:
  search_pages_browsing_module:
    search_page_urls_builder_module:
      search_page_url_templates:
        - https://www.jumia.com.eg/catalog/?q={}
    poster_post_identifiers_retriever_module:
      regex: jumia.com.eg\/(.+).html
    post_identifiers_retriever_module:
      regex: jumia.com.eg\/(.+).html
  post_information_retriever_module:
    post_url_template: https://www.jumia.com.eg/{}.html